### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by portokallidis** [jsoverson/grunt-plato#29]
$ npm install --save-dev grunt-plato
npm ERR! Error: Invalid version: "0.2"
npm ERR!     at Object.module.exports.fixVersionField (/usr/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:183:13)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:30:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:15)
npm ERR!     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:342:33)
npm ERR!     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:331:40
npm ERR!     at evalmachine.<anonymous>:272:14
npm ERR!     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-44-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "--save-dev" "grunt-plato"
npm ERR! cwd /home/nporto/projects/carre-edu
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/nporto/projects/carre-edu/npm-debug.log
npm ERR! not ok code 0

**Comment by portokallidis** [comment]
My bad! my package version had 0.2 , did a google search and found that correct versioning includes 3 parts so i changed to 0.2.0 and works!
