### ISSUE TITLE
ReferenceError: Symbol is not defined

### ISSUE THREAD

**Issue by andre-ferreira-qlik** [jsoverson/grunt-plato#34]
Hi, 

Was wondering if you could point me in the right direction regarding this one.
Loading "plato.js" tasks...ERROR

> > ReferenceError: Symbol is not defined

npm version 1.4.28
node version v0.10.32

Registering "grunt-plato" local Npm module tasks.
Reading /Users/xxx/Documents/work/projectX/grunt/node_modules/grunt-plato/package.json...OK
Parsing /Users/xxx/Documents/work/projectX/grunt/node_modules/grunt-plato/package.json...OK
Loading "plato.js" tasks...ERROR

> > ReferenceError: Symbol is not defined
> >   at /Users/xxx/Documents/work/projectX/grunt/node_modules/grunt-plato/node_modules/plato/node_modules/typhonjs-escomplex/node_modules/typhonjs-escomplex-module/node_modules/typhonjs-escomplex-commons/dist/utils/Enum.js:183:12
> >   at Object.<anonymous> (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt-plato/node_modules/plato/node_modules/typhonjs-escomplex/node_modules/typhonjs-escomplex-module/node_modules/typhonjs-escomplex-commons/dist/utils/Enum.js:190:2)
> >   at Module._compile (module.js:456:26)
> >   at Object.Module._extensions..js (module.js:474:10)
> >   at Module.load (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
> >   at Function.Module._load (module.js:312:12)
> >   at Module.require (module.js:364:17)
> >   at require (module.js:380:17)
> >   at Object.<anonymous> (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt-plato/node_modules/plato/node_modules/typhonjs-escomplex/node_modules/typhonjs-escomplex-module/node_modules/typhonjs-escomplex-commons/dist/types/ReportType.js:7:14)
> >   at Module._compile (module.js:456:26)
> >   at Object.Module._extensions..js (module.js:474:10)
> >   at Module.load (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
> >   at Function.Module._load (module.js:312:12)
> >   at Module.require (module.js:364:17)
> >   at require (module.js:380:17)
> >   at Object.<anonymous> (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt-plato/node_modules/plato/node_modules/typhonjs-escomplex/node_modules/typhonjs-escomplex-module/node_modules/typhonjs-escomplex-commons/dist/transform/formats/json/FormatJSONCheckstyle.js:15:19)
> >   at Module._compile (module.js:456:26)
> >   at Object.Module._extensions..js (module.js:474:10)
> >   at Module.load (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
> >   at Function.Module._load (module.js:312:12)
> >   at Module.require (module.js:364:17)
> >   at require (module.js:380:17)
> >   at Object.<anonymous> (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt-plato/node_modules/plato/node_modules/typhonjs-escomplex/node_modules/typhonjs-escomplex-module/node_modules/typhonjs-escomplex-commons/dist/transform/TransformFormat.js:15:29)
> >   at Module._compile (module.js:456:26)
> >   at Object.Module._extensions..js (module.js:474:10)
> >   at Module.load (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
> >   at Function.Module._load (module.js:312:12)
> >   at Module.require (module.js:364:17)
> >   at require (module.js:380:17)
> >   at Object.<anonymous> (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt-plato/node_modules/plato/node_modules/typhonjs-escomplex/node_modules/typhonjs-escomplex-module/node_modules/typhonjs-escomplex-commons/dist/module/report/AbstractReport.js:9:24)
> >   at Module._compile (module.js:456:26)
> >   at Object.Module._extensions..js (module.js:474:10)
> >   at Module.load (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
> >   at Function.Module._load (module.js:312:12)
> >   at Module.require (module.js:364:17)
> >   at require (module.js:380:17)
> >   at Object.<anonymous> (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt-plato/node_modules/plato/node_modules/typhonjs-escomplex/node_modules/typhonjs-escomplex-module/node_modules/typhonjs-escomplex-commons/dist/module/report/ModuleReport.js:11:24)
> >   at Module._compile (module.js:456:26)
> >   at Object.Module._extensions..js (module.js:474:10)
> >   at Module.load (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
> >   at Function.Module._load (module.js:312:12)
> >   at Module.require (module.js:364:17)
> >   at require (module.js:380:17)
> >   at Object.<anonymous> (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt-plato/node_modules/plato/node_modules/typhonjs-escomplex/node_modules/typhonjs-escomplex-module/dist/Plugins.js:17:21)
> >   at Module._compile (module.js:456:26)
> >   at Object.Module._extensions..js (module.js:474:10)
> >   at Module.load (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
> >   at Function.Module._load (module.js:312:12)
> >   at Module.require (module.js:364:17)
> >   at require (module.js:380:17)
> >   at Object.<anonymous> (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt-plato/node_modules/plato/node_modules/typhonjs-escomplex/node_modules/typhonjs-escomplex-module/dist/ESComplexModule.js:15:16)
> >   at Module._compile (module.js:456:26)
> >   at Object.Module._extensions..js (module.js:474:10)
> >   at Module.load (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
> >   at Function.Module._load (module.js:312:12)
> >   at Module.require (module.js:364:17)
> >   at require (module.js:380:17)
> >   at Object.<anonymous> (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt-plato/node_modules/plato/node_modules/typhonjs-escomplex/dist/ESComplex.js:15:24)
> >   at Module._compile (module.js:456:26)
> >   at Object.Module._extensions..js (module.js:474:10)
> >   at Module.load (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
> >   at Function.Module._load (module.js:312:12)
> >   at Module.require (module.js:364:17)
> >   at require (module.js:380:17)
> >   at Object.<anonymous> (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt-plato/node_modules/plato/node_modules/typhonjs-escomplex/dist/index.js:7:18)
> >   at Module._compile (module.js:456:26)
> >   at Object.Module._extensions..js (module.js:474:10)
> >   at Module.load (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
> >   at Function.Module._load (module.js:312:12)
> >   at Module.require (module.js:364:17)
> >   at require (module.js:380:17)
> >   at Object.<anonymous> (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt-plato/node_modules/plato/lib/reporters/complexity/index.js:3:17)
> >   at Module._compile (module.js:456:26)
> >   at Object.Module._extensions..js (module.js:474:10)
> >   at Module.load (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
> >   at Function.Module._load (module.js:312:12)
> >   at Module.require (module.js:364:17)
> >   at require (module.js:380:17)
> >   at Object.<anonymous> (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt-plato/node_modules/plato/lib/plato.js:27:20)
> >   at Module._compile (module.js:456:26)
> >   at Object.Module._extensions..js (module.js:474:10)
> >   at Module.load (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
> >   at Function.Module._load (module.js:312:12)
> >   at Module.require (module.js:364:17)
> >   at require (module.js:380:17)
> >   at Object.module.exports (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt-plato/tasks/plato.js:13:15)
> >   at loadTask (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/lib/grunt/task.js:318:10)
> >   at /Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/lib/grunt/task.js:354:7
> >   at Array.forEach (native)
> >   at loadTasks (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/lib/grunt/task.js:353:11)
> >   at Task.task.loadNpmTasks (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/lib/grunt/task.js:401:5)
> >   at Object.module.exports (/Users/xxx/Documents/work/projectX/grunt/tasks/plato.js:58:9)
> >   at loadTask (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/lib/grunt/task.js:318:10)
> >   at /Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/lib/grunt/task.js:354:7
> >   at Array.forEach (native)
> >   at loadTasks (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/lib/grunt/task.js:353:11)
> >   at Task.task.loadTasks (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/lib/grunt/task.js:365:5)
> >   at Object.module.exports (/Users/xxx/Documents/work/projectX/grunt/Gruntfile.js:26:9)
> >   at loadTask (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/lib/grunt/task.js:318:10)
> >   at Task.task.init (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/lib/grunt/task.js:437:5)
> >   at Object.grunt.tasks (/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/lib/grunt.js:111:8)
> >   at Object.module.exports [as cli](/Users/xxx/Documents/work/projectX/grunt/node_modules/grunt/lib/grunt/cli.js:27:9)
> >   at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:45:20)
> >   at Module._compile (module.js:456:26)
> >   at Object.Module._extensions..js (module.js:474:10)
> >   at Module.load (module.js:356:32)
> >   at Function.Module._load (module.js:312:12)
> >   at Function.Module.runMain (module.js:497:10)
> >   at startup (node.js:119:16)
> >   at node.js:906:3
> > Loading "plato.js" tasks...OK
> > No tasks were registered or unregistered.

**Comment by alundiak** [comment]
Any updates on it? @andre-ferreira-qlik @jsoverson  @donnanicolas 
I don't have this error locally, but when I run on Bamboo CI server, I have an error. No idea, but still debugging, troubleshooting. My Bamboo environment is:
```
grunt-plato v1.4.0

node v0.10.32
npm v1.4.28
grunt-cli v0.1.13
grunt v0.4.5
bower 1.3.12
Linux (Docker instance)
```

plato task

```
plato: {
	target: {
		options : {
			complexity : {
				logicalor : false,
				switchcase : false,
				forin : true,
				trycatch : true
			}
		},
		files: {
			'reports': ['src/main/webapp/app/*.js', 'src/main/webapp/common/**/*.js']
		}
	}
}
```

**Comment by alundiak** [comment]
Looks like bug is not reproduced as written starting Node 0.12.x:
https://github.com/lebab/lebab/issues/34#issuecomment-94061578
> Add symbols to release build
0.12 changelog

https://raw.githubusercontent.com/joyent/node/v0.12.0/ChangeLog
